### ISSUE TITLE
Build failure traced back to old commit

### ISSUE THREAD

**Issue by terror** [bitvecto-rs/bitvec#105]
When building bitvec from source, I'm getting a build error and after running `git bisect` I could trace it back down to this commit -> 47d6e1970c193abb148cf2271ebbd1b3665308a4

Here is the message I'm receiving
```
error[E0034]: multiple applicable items in scope
  --> src/mem.rs:28:19
   |
28 |     const INDX: u8 = Self::BITS.trailing_zeros() as u8;
   |                      ^^^^^^^^^^ multiple `BITS` found
```

OS: macOS Big Sur 10.16 20C69 x86_64
cargo --version: cargo 1.36.0 (c4fcfb725 2019-05-15)

Note that I'm using Big Sur which may play a role in the cause of this error.

**Comment by EthanYidong** [comment]
Actually, this is due to a breaking change in `funty` https://github.com/myrrlyn/funty/commit/b87325bce3dac89c95e02e400d4d037a9137a2b6, which ads a `BITS` constant that `bitvec` is glob importing

**Comment by Zorotic** [comment]
> Actually, this is due to a breaking change in `funty` [myrrlyn/funty@b87325b](https://github.com/myrrlyn/funty/commit/b87325bce3dac89c95e02e400d4d037a9137a2b6), which ads a `BITS` constant that `bitvec` is glob importing. Version 1.1.0 of funty works fine, so as a temporary workaround, add `funty = "=1.1.0"` to your `Cargo.toml`

You are a live saver :100:

**Comment by iptq** [comment]
Maybe it would be a good idea to pin to minor versions of dependencies as well, since glob-imports are used in code?

**Comment by matthiasbeyer** [comment]
> Maybe it would be a good idea to pin to minor versions of dependencies as well, since glob-imports are used in code?

I guess the proper way would not to use glob imports at all?

**Comment by iptq** [comment]
Wait, I looked into it a bit and it doesn't look like a glob import; the problem is in `src/mem.rs`, the `BitMemory` trait is declaring an associated member called `BITS`:

```rs
const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
```

But `IsNumber` which is a super-super-super-trait of `BitMemory` (indirectly through `IsUnsigned` and `IsInteger`), has been [updated in version 1.2 of funty](https://docs.rs/funty/1.2.0/src/funty/lib.rs.html#144) to include a `BITS` member as well, implementing the same functionality:

```rs
const BITS: u32;
```

Looks like both crates seem to just be waiting on the stabilization of the `::BITS` member in the standard library, but for now, the rust compiler can't disambiguate between the two, so it raises the error.

First off, this won't happen if versions are pinned to at least minor version, since the semver specification allows minor versions to introduce new functionality into the public API:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

This means that if you don't pin to minor versions, your dependencies could cause collisions like what just happened. Since this is a library and not a bin, it can't take advantage of a lockfile so it should ideally pin to versions as exact as possible.

As for the actual problem, ultimately the decision is up to the maintainers but I think it'll be OK to depend on the `IsNumber` implementation since it's the same so there's not a need to reimplement it if depending on funty >=1.2.

**Comment by sunjay** [comment]
Also affected the [turtle crate](https://github.com/sunjay/turtle). Broke [our build on master](https://dev.azure.com/sunjayv/turtle/_build/results?buildId=917&view=logs&j=3df22538-2a64-5d6a-ccd1-435dcd87d567&t=6dd4ac93-7a6c-5536-f798-7b58532da147&l=2144). We fixed it by updating to bitvec 0.21.0.

**Comment by thiolliere** [comment]
can't we just explicit usage of BITS in bitvec to avoid ambiguity ? https://github.com/bitvecto-rs/bitvec/pull/109

**Comment by thiolliere** [comment]
the above fix is base on 0.20, I open a fix for 0.20.1 https://github.com/bitvecto-rs/bitvec/pull/110

**Comment by myrrlyn** [comment]
I completely forgot to check up on this after publishing the patch releases, which is 100% my bad.

Is everyone fixed now

**Comment by tarcieri** [comment]
@myrrlyn yep, thanks!
